/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import java.awt.Container;
import meujogo.Modelo.Sounds;
import java.awt.Dimension;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.SwingConstants;
import java.awt.Point;
import javax.swing.BoxLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Paulo Henrique
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    public Menu() {
    	setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jPanel3 = new javax.swing.JPanel();
        BotaoJogar = new javax.swing.JButton();
        BotaoSair = new javax.swing.JButton();
        BotaoSair.setSize(new Dimension(1024, 0));
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuOpcoes = new javax.swing.JMenu();
        botaoSair = new javax.swing.JMenuItem();
        MenuSobre = new javax.swing.JMenu();
        Desenvolvedores = new javax.swing.JMenuItem();
        Instrucoes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Principal");
        setExtendedState(5);
        setPreferredSize(new java.awt.Dimension(1024, 728));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 1018, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 679, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        BotaoJogar.setBackground(new java.awt.Color(0, 0, 0));
        BotaoJogar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BotaoJogar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoJogar.setText("Jogar");
        BotaoJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoJogarActionPerformed(evt);
            }
        });
        BotaoJogar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotaoJogarKeyPressed(evt);
            }
        });

        BotaoSair.setBackground(new java.awt.Color(0, 0, 0));
        BotaoSair.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BotaoSair.setForeground(new java.awt.Color(255, 255, 255));
        BotaoSair.setText("Fechar");
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(265)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(BotaoJogar, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(BotaoSair, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
        			.addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap(579, Short.MAX_VALUE)
        			.addComponent(BotaoJogar)
        			.addGap(18)
        			.addComponent(BotaoSair)
        			.addGap(20))
        );
        jPanel3.setLayout(jPanel3Layout);

        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1Layout.setHorizontalGroup(
        	jLayeredPane1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
        			.addGroup(jLayeredPane1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jPanel2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 1018, Short.MAX_VALUE)
        				.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 1018, Short.MAX_VALUE))
        			.addGap(747))
        );
        jLayeredPane1Layout.setVerticalGroup(
        	jLayeredPane1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jLayeredPane1Layout.createSequentialGroup()
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 679, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        		.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1.setLayout(jLayeredPane1Layout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        			.addComponent(jLayeredPane1, GroupLayout.PREFERRED_SIZE, 1113, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jLayeredPane1, GroupLayout.PREFERRED_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel1.setLayout(jPanel1Layout);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(null);

        MenuOpcoes.setBackground(new java.awt.Color(0, 0, 0));
        MenuOpcoes.setBorder(null);
        MenuOpcoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons 1/joystick.png"))); // NOI18N
        MenuOpcoes.setText("Opções");

        botaoSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons 1/door_in.png"))); // NOI18N
        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });
        MenuOpcoes.add(botaoSair);

        jMenuBar1.add(MenuOpcoes);

        MenuSobre.setBackground(new java.awt.Color(0, 0, 0));
        MenuSobre.setBorder(null);
        MenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons 1/information.png"))); // NOI18N
        MenuSobre.setText("Sobre");

        Desenvolvedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        Desenvolvedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons 1/user_comment.png"))); // NOI18N
        Desenvolvedores.setText("Desenvolvedores");
        Desenvolvedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesenvolvedoresActionPerformed(evt);
            }
        });
        Desenvolvedores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DesenvolvedoresKeyPressed(evt);
            }
        });
        MenuSobre.add(Desenvolvedores);

        Instrucoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        Instrucoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons 1/keyboard.png"))); // NOI18N
        Instrucoes.setText("Instruções");
        Instrucoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstrucoesActionPerformed(evt);
            }
        });
        MenuSobre.add(Instrucoes);

        jMenuBar1.add(MenuSobre);

        setJMenuBar(jMenuBar1);
        getContentPane().setLayout(new BoxLayout(getContentPane(), BoxLayout.X_AXIS));
        getContentPane().add(jPanel1);

        setSize(new Dimension(1024, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoJogarActionPerformed
    	Container jogo = new meujogo.Container();  //criado objeto container importado.
    	jogo.setVisible(true); //deixando a tela visivel
    	dispose(); //escondendo a tela do jogo
    	Sounds p = new Sounds();//instanciamento do objeto que fará o som tocar no inicio do jogo
    	p.executaSom("res\\CharlieBrownJr.WAV"); //metodo que dá inicio ao som.
    }//GEN-LAST:event_BotaoJogarActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        System.exit(0); //saindo do jogo
    }//GEN-LAST:event_botaoSairActionPerformed

    private void BotaoJogarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotaoJogarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoJogarKeyPressed

    private void DesenvolvedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesenvolvedoresActionPerformed
        Desenvolvedores tela = new Desenvolvedores();
        tela.setVisible(true);    //abrindo um popup mostrando os desenvolvedores.
    }//GEN-LAST:event_DesenvolvedoresActionPerformed

    private void InstrucoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstrucoesActionPerformed
        Instrucoes telaInstrucoes = new Instrucoes(); //abrindo um popup mostrando os comandos do jogo.
        telaInstrucoes.setVisible(true);
    }//GEN-LAST:event_InstrucoesActionPerformed

    private void DesenvolvedoresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DesenvolvedoresKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesenvolvedoresKeyPressed

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotaoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoJogar;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JMenuItem Desenvolvedores;
    private javax.swing.JMenuItem Instrucoes;
    private javax.swing.JMenu MenuOpcoes;
    private javax.swing.JMenu MenuSobre;
    private javax.swing.JMenuItem botaoSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
